version: '3'

services:
  mysql:
    container_name: ${PROJECT_NAME}_mysql
    image: mariadb
    volumes:
      - database:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpback

  phpmyadmin:
    container_name: ${PROJECT_NAME}_phpmyadmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
      VIRTUAL_HOST: phpmyadmin.${PROJECT_NAME}.local
    networks:
      - wpback
      - wpfront

  wordpress:
    container_name: ${PROJECT_NAME}_wp
    depends_on:
      - mysql
    image: bitnami/wordpress:latest
    restart: always
    volumes:
      - ./wp:/bitnami/wordpress
      # - ./config/apache/httpd.conf:/opt/bitnami/apache/conf/httpd.conf
      # - ./config/php/php.ini:/opt/bitnami/php/conf/php.ini
    environment:
      VIRTUAL_HOST: ${PROJECT_NAME}.local
      VIRTUAL_PORT: 80
      MARIADB_HOST: mysql
      MARIADB_PORT_NUMBER: 3306
      WORDPRESS_DATABASE_NAME: wordpress
      WORDPRESS_DATABASE_USER: wordpress
      WORDPRESS_DATABASE_PASSWORD: wordpress
      WORDPRESS_USERNAME: admin
      WORDPRESS_PASSWORD: admin
      WORDPRESS_EMAIL: admin@admin.local
      WORDPRESS_BLOG_NAME: Eu amo Docker!
    networks:
      - wpback
      - wpfront

  db-backup:
    container_name: ${PROJECT_NAME}_backup
    depends_on:
      - mysql
    image: databack/mysql-backup
    restart: always
    volumes:
      - ./backups:/db
    environment:
      - DB_DUMP_TARGET=/db
      - DB_USER=wordpress
      - DB_PASS=wordpress
      - DB_DUMP_FREQ=30
      - DB_DUMP_BEGIN=+1
      - DB_SERVER=mysql
    networks:
      - wpback

networks:
  wpback:
  wpfront:
    external:
      name: proxy
volumes:
  database: